### ISSUE TITLE
SAM Inference fails: Client Error: Not Found for url: http://192.168.50.217:8080/data/upload/1/aa6a641e-OIP.jpeg"

### ISSUE THREAD

**Issue by jeffrymahbuubira** [HumanSignal/label-studio-ml-backend#400]
Hello,

I am trying to use the SAM ML Backend in Label Studio. I have followed the guide from [Getting Started Using Segment Anything with Label Studio](https://labelstud.io/blog/get-started-using-segment-anything/#installing-the-sam-ml-backend). I did everything as instructed, but every time I try to label using Auto-Detect, it fails to create any segmentation labels.

Here is the log:

[2024-01-09 07:36:11,470] [DEBUG] [label_studio_ml.api::log_response_info::143] Response body: b'{"detail":"HTTPError: 404 Client Error: Not Found for URL: http://192.168.50.217:8080/data/upload/1/aa6a641e-OIP.jpeg","request":{},"result":{"traceback":"Traceback (most recent call last):\\n File \\"/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py\\", line 39, in exception_f\\n return f(*args, **kwargs)\\n File \\"/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py\\", line 61, in _predict\\n predictions = model.predict(tasks, context=context, **params)\\n File \\"/app/model.py\\", line 48, in predict\\n predictor_results = PREDICTOR.predict(\\n File \\"/app/sam_predictor.py\\", line 195, in predict\\n return self.predict_sam(img_path, point_coords, point_labels, input_box)\\n File \\"/app/sam_predictor.py\\", line 167, in predict_sam\\n self.set_image(img_path, calculate_embeddings=False)\\n File \\"/app/sam_predictor.py\\", line 83, in set_image\\n image_path = get_image_local_path(\\n File \\"/usr/local/lib/python3.8/site-packages/label_studio_ml/utils.py\\", line 66, in get_image_local_path\\n image_local_path = get_local_path(\\n File \\"/usr/local/lib/python3.8/site-packages/label_studio_tools/core/utils/io.py\\", line 105, in get_local_path\\n r.raise_for_status()\\n File \\"/usr/local/lib/python3.8/site-packages/requests/models.py\\", line 1021, in raise_for_status\\n raise HTTPError(http_error_msg, response=self)\\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for URL: http://192.168.50.217:8080/data/upload/1/aa6a641e-OIP.jpeg\\n"},"status":500}\n'

Here is my docker-compose.yml: 

```
version: "3.8"

services:
  server:
    container_name: server
    image: humansignal/sam:v0
    build:
      context: .
      shm_size: "4gb"
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    environment:
      # Change this to your model name
      - SAM_CHOICE=MobileSAM
      - LOG_LEVEL=DEBUG
      # Add these variables if you want to access the images stored in Label Studio
      - LABEL_STUDIO_HOST=http://192.168.50.217:8080
      - LABEL_STUDIO_ACCESS_TOKEN=8681fe6e75faaf151c8f13588c6ee977586dfba9
    ports:
      - 9090:9090
    volumes:
      - "./data/server:/data"
```

I tried to open the image I upload in http://192.168.50.217:8080/data/upload/1/aa6a641e-OIP.jpeg, but it can't open the image and Access Error: 404 -- Not Found

Any suggestions and help would be greatly appreciated. Thank you!
