### ISSUE TITLE
How to pull the images named 'humansignal/yolo:v0' at yolo/docker-compose

### ISSUE THREAD

**Issue by Lyn4ever29** [HumanSignal/label-studio-ml-backend#723]
when I run ```docker-compose up ```,there is an error 
```
Error response from daemon: pull access denied for humansignal/yolo, repository does not exist or may require 'docker login'
```
the docker-compose.yaml is below:
```yaml
version: "3.8"

services:
  yolo:
    container_name: yolo
    image: humansignal/yolo:v0
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}
    environment:
      # specify these parameters if you want to use basic auth for the model server
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      # set the log level for the model server
      - LOG_LEVEL=DEBUG
      # any other parameters that you want to pass to the model server
      - ANY=PARAMETER
      # specify the number of workers and threads for the model server
      - WORKERS=1
      - THREADS=8
      # specify the model directory (likely you don't need to change this)
      - MODEL_DIR=/data/models
      - PYTHONPATH=/app

      # Specify the Label Studio URL and API key to access
      # uploaded, local storage and cloud storage files.
      # Do not use 'localhost' or '127.0.0.1' as it does not work within Docker containers.
      # Use prefix 'http://' or 'https://' for the URL always.
      # Determine the actual IP using 'ifconfig' (Linux/Mac) or 'ipconfig' (Windows).
      # or you can try http://host.docker.internal:<label-studio-port> if you run LS on the same machine
      - LABEL_STUDIO_URL=http://host.docker.internal:8080
      - LABEL_STUDIO_API_KEY=

      # YOLO parameters

      # Allow to use custom `model_path` in labeling configurations
      - ALLOW_CUSTOM_MODEL_PATH=true
      # Show matplotlib debug plot for YOLO predictions
      - DEBUG_PLOT=false
      # Default score threshold, which is used to filter out low-confidence predictions,
      # you can change it in the labeling configuration using `model_score_threshold` parameter in the control tags
      - MODEL_SCORE_THRESHOLD=0.5
      # Model root directory, where the YOLO model files are stored
      - MODEL_ROOT=/app/models
    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
      - "./models:/app/models"
      - "./cache_dir:/app/cache_dir"
```

**Comment by mzizzi** [comment]
Remove the image key from the services def and let docker-compose build the image locally.

```
services:
  yolo:
    container_name: yolo
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}
```

`docker compose up --build` will build the image before starting the service.
