### ISSUE TITLE
exec /app/start.sh: no such file or directory

### ISSUE THREAD

**Issue by kthenurseone** [HumanSignal/label-studio-ml-backend#746]
When I am trying to use humansignal/ml-backend:v0 , this happens please help...

```
2025-04-06 18:29:37 exec /app/start.sh: no such file or directory
2025-04-06 18:32:52 exec /app/start.sh: no such file or directory
2025-04-06 18:42:39 exec /app/start.sh: no such file or directory
```

**Comment by michaelballou** [comment]
I was able to get around this by changing the last line in the Dockerfile to this like the other examples:

# CMD ["/app/start.sh"]
CMD gunicorn --preload --bind :$PORT --workers 1 --threads 8 --timeout 0 _wsgi:app

**Comment by pinyinjj** [comment]
> I was able to get around this by changing the last line in the Dockerfile to this like the other examples:
> 
> Remove -> CMD ["/app/start.sh"] CMD gunicorn --preload --bind :$PORT --workers 1 --threads 8 --timeout 0 _wsgi:app

This works! Love

**Comment by felimet** [comment]
## Fail-safe workaround

1. Modify [docker-compose.yml](https://github.com/HumanSignal/label-studio-ml-backend/blob/master/label_studio_ml/examples/segment_anything_2_image/docker-compose.yml)
```yaml
environment:
      # specify these parameters if you want to use basic auth for the model server
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      ...
      - LABEL_STUDIO_URL=
      - LABEL_STUDIO_API_KEY=
    command: ["/bin/bash", "-lc", "sed -i 's/\\r$//' /app/start.sh && exec /bin/bash /app/start.sh"]
    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
```   
2. Modify [start.sh](https://github.com/HumanSignal/label-studio-ml-backend/blob/master/label_studio_ml/examples/segment_anything_2_image/start.sh)
```bash
#!/bin/bash

# Execute the gunicorn command
exec gunicorn --bind :${PORT:-9090} --workers ${WORKERS:-1} --threads ${THREADS:-4} --timeout 0 --pythonpath '/app' _wsgi:app
```

3. Modify [Dockerfile]( #url) 
```Dockerfile
...
COPY . ./
RUN sed -i 's/\r$//' /app/start.sh && chmod +x /app/start.sh

WORKDIR ../sam2

CMD ["/app/start.sh"]```
