### ISSUE TITLE
CUDA with multiprocessing

### ISSUE THREAD

**Issue by Fireblossom** [HumanSignal/label-studio-ml-backend#79]
Greetings,

I'm getting this error when use ml backend with PyTorch.

`RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method`

I see [there](https://stackoverflow.com/questions/48822463/how-to-use-pytorch-multiprocessing) is a solution.
I try to fix it [here](https://github.com/Fireblossom/label-studio-ml-backend/commit/ab6eda363c28bb5d2b237b2d47c8f5d5be3e0e63#diff-32ea3090e98a3229619bf0947ca5f38c97b052b597636e32de195038a9547460) and it works fine on my machine.
Do you think my solution is feasible?
If so, I can make a PR ;-)

**Comment by KonstantinKorotaev** [comment]
Hi @Fireblossom 
Your solution is good, please make a PR

**Comment by EgShes** [comment]
Where is this now? I face the same issue using segment-anything model

The error I get

```
sam-server_1          | Traceback (most recent call last):
sam-server_1          |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
sam-server_1          |     return f(*args, **kwargs)
sam-server_1          |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 61, in _predict
sam-server_1          |     predictions = model.predict(tasks, context=context, **params)
sam-server_1          |   File "/app/model.py", line 48, in predict
sam-server_1          |     predictor_results = PREDICTOR.predict(
sam-server_1          |   File "/app/sam_predictor.py", line 244, in predict
sam-server_1          |     return self.predict_sam(img_path, point_coords, point_labels, input_box)
sam-server_1          |   File "/app/sam_predictor.py", line 216, in predict_sam
sam-server_1          |     self.set_image(img_path, calculate_embeddings=False)
sam-server_1          |   File "/app/sam_predictor.py", line 139, in set_image
sam-server_1          |     self.predictor.set_image(image)
sam-server_1          |   File "/usr/local/lib/python3.8/site-packages/mobile_sam/predictor.py", line 57, in set_image
sam-server_1          |     input_image_torch = torch.as_tensor(input_image, device=self.device)
sam-server_1          |   File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 235, in _lazy_init
sam-server_1          |     raise RuntimeError(
sam-server_1          | RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

Here is the docker-compose service

```
  sam-server:
    image: humansignal/sam:v0
    build:
      context: .
      shm_size: '4gb'
    deploy:
      resources:
        limits:
            memory: 8G
        reservations:
            memory: 4G
    environment:
      # Change this to your model name
      - SAM_CHOICE=MobileSAM
      - LOG_LEVEL=DEBUG
      # Add these variables if you want to access the images stored in Label Studio
      - LABEL_STUDIO_HOST=http://labelstudio-server:8080
      - LABEL_STUDIO_ACCESS_TOKEN=token
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 9090:9090
    volumes:
      - "./data/server:/data"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
